<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'webpack_encore.exception_listener' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\webpack-encore-bundle\\src\\EventListener\\ExceptionListener.php';

return $this->privates['webpack_encore.exception_listener'] = new \Symfony\WebpackEncoreBundle\EventListener\ExceptionListener(($this->privates['webpack_encore.entrypoint_lookup_collection'] ?? $this->load('getWebpackEncore_EntrypointLookupCollectionService.php')), [0 => '_default']);
