<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4FdYEQi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4FdYEQi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4FdYEQi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4FdYEQi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4FdYEQi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4FdYEQi',
    'container.build_id' => 'd6e32743',
    'container.build_time' => 1587850846,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4FdYEQi');
